language: go
go:
- 1.7
dist: trusty
env:
- PLATFORM=linux-amd64
- PLATFORM=linux-arm
sudo: required
script:
- bash -ex .travis-ci.sh
deploy:
  provider: releases
  api_key:
    secure: Y6qjOGGMNLr2Asvyb8tbqsWj4z3c4ypOC5KzkxyyTNH4yuohA+rRvuwMoSabr3QXbXZAKbfChd13FY3ZCE5l0kwq0TBrd805ggfXCkDsRUBE5xiF7ccRIrFhyr8cd9XFAzZAd9wPjoPoqq5I7/tNZNQ7oeM+6jtDOyI4XJ34fuct1DXxCAVVWmbcqXJ/ywKmlOlD36otON19wTdH+wsl4Y2KbNYUqLJvhK4rOShDOTvZe/LxrlOddOoCJjDOF2L9fCmPnDEaWlVD59x0gXUa5GHDqnfLB0l925ef+t5cD0WNEYm0YIS+eJQTFQRZH4eUSQLcUdlB4skvlNYsCmr5J0KROjqzIQWQ6J5AmUaHVgo/RUB82ituVjKBJNPo4Hbhs17H+UNHjZlt6n/W+ocYbcUBhqT1K+Z7kFg02NQ8rdW+cnR+PiZltGBZp+L51oNrqAldRGSHg3HOfNNc1tKPAoaFxPzg14JblaDgI7AXE+/nnjaO0BhkjvWfuythH6noagd5LFwLc/MpUlDNSjndX09A12n5B78Na2rzn5nsjDSA1rP1kyciE88WhYQ/c/sn0hvKR1m7+1//7uZqBfW5qNpoNRiyzHslgo06yQ/VTbEXsmwno0J/wh5oloiUU1Dn0P+a6iG0+qJHAnW5WjK37Lhj8wCPG3o7GV/fOFg3II0=
  file:
    - "wherearetheyflyingto-linux-amd64"
    - "wherearetheyflyingto-linux-arm"
  on:
    repo: andrewl/wherearetheyflyingto
