language: go

go:
  - 1.5

env:
  - ARCH=x86
  - ARCH=arm

sudo: required

script:
  - "bash -ex .travis-ci.sh"

deploy:
  provider: releases
  api_key: "4300cc848285ba164f9528c27989bbc7b22004fc"
  file:
    - "wherearetheyflyingto"
    - "wherearetheyflyingto-arm"
  skip_cleanup: true
  on:
    tags: true
